### ISSUE TITLE
Add dot notation

### ISSUE THREAD

**Issue by S1SYPHOS** [sylvainjule/kirby-markdown-field#100]
Hey there,
when changing a single font option, like this:

```
'community.markdown-field.font' => [
  'family' => 'sans-serif',
]
```

.. the other options are overwritten, and I get this:

![image](https://user-images.githubusercontent.com/12161504/95015863-bc85cb00-064f-11eb-9161-28685e04d25f.png)

.. so I'd like to do it this way (without affecting the other options):

`'community.markdown-field.font.family' => 'sans-serif'`

**Comment by sylvainjule** [comment]
Hello, I can't reproduce it in my "plugins sandbox" + a fresh Starterkit with Kirby 3.5.

It shouldn't overwrite all keys indeed but only replace the key you've explicitely set, I'm using [A::merge() here](https://github.com/sylvainjule/kirby-markdown-field/blob/b5423e25d772b15cc3b1727498bd5b0f69db5f22/lib/fields/markdown.php#L46) from [Kirby's toolkit](https://getkirby.com/docs/reference/tools/a/merge) and it works fine in my tests.

Please reopen if the issue still occur for you in 3.5.
