### ISSUE TITLE
Styling / scrollbar issue

### ISSUE THREAD

**Issue by eXpl0it3r** [sylvainjule/kirby-markdown-field#104]
## Steps to reproduce

- Get the starterkit with Kirby 3.4.4 (maybe other versions also apply)
- Change one of the blueprint to take a `type: markdown` field
- Open the panel page
- Start entering some text

## Actual Behavior

- The height of the text box is to small to start with
- The scrollbar is shown from the start
- After entering two lines of text, the second line is already vanishing to the top, out of the text box
- Doesn't matter if the font was set as regular or small

![image](https://user-images.githubusercontent.com/920861/98438512-06e4e680-20eb-11eb-93a3-b8c247bd6043.png)
![image](https://user-images.githubusercontent.com/920861/98438459-a81f6d00-20ea-11eb-8cd2-9708f72edfff.png)

## Expected Behavior

- The height should at least cover two lines of text from the start
- There isn't really a need for a scrollbar if the text box keeps expanding correctly
- The text should not be moving out of view (after two lines of text), but the text box should expand to the correct size

**Comment by eXpl0it3r** [comment]
I just took a look at [CodeMirror's documentation](https://codemirror.net/doc/manual.html) and setting the `scrollbarStyle` to `null` instead of `native` already got rid of the scrollbar for me.
But there's still some spacing issue, which I guess comes from the toolbar being in the same space as the text entry field.

**Comment by eXpl0it3r** [comment]
I've some ["fixes"](https://github.com/sylvainjule/kirby-markdown-field/compare/master...eXpl0it3r:bugfix/scroll-issue), but they seem more like patches than actually solving the issue. Posting here, just in case someone else is interested in them. 😅

**Comment by sylvainjule** [comment]
The scrollbar issue is fixed. 

I have added a [size option](https://github.com/sylvainjule/kirby-markdown-field#35-size).
