### ISSUE TITLE
CSS for size presets 'large' and 'huge'

### ISSUE THREAD

**Issue by sebastiangreger** [sylvainjule/kirby-markdown-field#105]
@sylvainjule, great job on the recent updates -- thank you! :+1:

Since the pre-1.0.7 default for the markdown field size was `large`, I tried to restore the previous appearance by overriding the new default (`small`; awesome option of creating Markdown fields that look like an input field!) by applying option `'community.markdown-field.size' => 'large'` but that did not yield any effect; nor did using `size: large` in the affected blueprints.

It appears that with [this commit](https://github.com/sylvainjule/kirby-markdown-field/commit/b5423e25d772b15cc3b1727498bd5b0f69db5f22), the required CSS styles for large and huge markdown fields were removed. As you describe in the Readme, there is of course the possibility to add a custom panel CSS, but considering an easy update path and equivalency with Kirby's `textarea` field, would it perhaps be possible to reintroduce these two additional sizes of `large` and `huge` to be provided out-of-the-box in the plugin's CSS?

**Comment by sebastiangreger** [comment]
Fantastic! Thank you for the update :bow:

**Comment by sylvainjule** [comment]
You're welcome!
