### ISSUE TITLE
[next] Vertical scroll position lost when unfocusing Firefox

### ISSUE THREAD

**Issue by sebastiangreger** [sylvainjule/kirby-markdown-field#115]
This happens on Firefox (both Linux and Windows, current version), but not on Chromium:

When editing a text longer than the screen height, the Panel's vertical scroll position gets lost when unfocusing the browser (e.g. switching to another application and then back). The view jumps to the top of the markdown field as the browser gets unfocused and remains there when switching back to the Firefox window.

The cursor, however, remains inside the markdown field and in the correct position and it is possible to resume typing after focus is back on Firefox -- after the first key stroke, the vertical scroll jumps back to put the current cursor position into view.

**To reproduce:**
- In FF, create a text long enough to grow the markdown field beyond viewport height
- Add some text in the bottom line
- Switch to some other application on the desktop (at this point, the vertical scroll of the browser jumps to the top bar of the markdown field)
- Switch back to the Firefox window (scroll remains where it is)
- Continue to type (vertical scroll jumps to where the cursor is)

**Expected behaviour:**
The vertical scroll of the panel would not change when switching desktop focus to some other app (as it does in Chromium)

**Comment by fabianmichael** [comment]
@sebastiangreger Thanks for reporting the Bug, I can replicate it. But I’m currently kind of clueless about what’s causing this. There have been some weird bugs with the way how Kirby’s panel is setup, i.e. the main view is inside a scrollable container with `position: absolute` and `transform: translateZ(0)` set. But even after removing these properties and declaring the `<html>` element as scroll container, the issue persists.

Also tried to a minimal example, but that worked without any issues. Will investigate this further, once I have a chance to do so. Really don't want to force anyone into using Chrome. :-P

**Comment by sebastiangreger** [comment]
@fabianmichael Sorry this took so long: yes, I can confirm the issue appears to be solved (currently only based on a quick test run; I would follow up with you in case glitches appear in daily use later...)

Thank you for your efforts! The `next` version of this plugin is such a pleasure to work with :pray:
