### ISSUE TITLE
Long content glitch

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#22]
Sometimes when I paste long content with a lot of formatting the upper half gets hidden. When triggering a rewrite via a click or browser resize, it gets fixed. Tested in latest Chrome, Firefox and Safari.

I have not yet found the exact length or formatting amount to reproduce it. You can find an example text on the bottom of this issue, though.

![markdown](https://user-images.githubusercontent.com/7975568/50479502-3bf45e00-09d7-11e9-8b26-7fc917b4fa4c.gif)

```
## Lorem Ipsum 

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.aaa

**Lorem Ipsum:**

- 2009: Finalistin beim internationalen Wettbewerb „Schömberger Fotoherbst für Reise- und Reportagefotografie“ mit ihrer Dokumentation der Arbeit der „Helfenden Hände e.V.“ in Nouakchott / Mauretanien. 
- Im September 2009 erstmalige Teilnahme an den IPA int ́l photography awards in New York; Ulrike Klumpps Arbeiten erreichten die Endrunde und damit ein „Honorable Mention“. 
- Diesen Erfolg konnte sie in den Folgejahren 2010 – 2015 wiederholen.
- Im Juli 2010 war ihr Projekt “SchwarzwaldMenschen” eines der vier Besten des Berliner Wettbewerbs “Halbtagsjob 2010”.
- 2011: Finalistin beim 11. „Schömberger Fotoherbst “ mit der Geschichte „Farm Glenorkie“.
- September 2011: 2. Platz der IPA New York, Kategorie Architektur / Stadtlandschaften.
- 2015: Finalistin beim 13. „Schömberger Fotoherbst“, Serie „Waisenhaus in Burundi“.

**Lorem Ipsum:**

- Ausstellung „Naturreine Interpretationen“ in der Kreissparkasse Freudenstadt, August 2007.
- Ausstellung „Anders sehen – anderes Sehen“ in Dornstetten, Frühjahr 2009. Die Serie entstand aus der ehrenamtlichen Dokumentation der Arbeit der „Helfenden Hände e.V.“ in Nouakchott/Mauretanien.
- Gruppenausstellung „Farbe in der Natur“ im Palmengarten Frankfurt, Oktober 2009.
- Teilnahme an der Internationalen Kalenderschau des Graphischen Klubs Stuttgart und am Calendar Fair der Japan Federation of Printing Industries mit einer Auftragsarbeit für die HOMAG Holzbearbeitungssysteme AG. Januar 2010.
- Ausstellung „ 7969 km Schwarzwald – Namibia“ in der Kulturfabrik in Schopfheim, 2012/13.
- Im Oktober 2013 eröffnete Ulrike Klumpp ihre eigene Fotogalerie in Baiersbronn. Neben ihren eigenen Fotoprojekten bietet die Galerie auch Raum, Ausstellungen anderer Fotokünstler zu präsentieren.
- Gemeinschaftsausstellung „Heimischer Hirsch“ – Kunstausstellung mit zeitgenössischer Malerei und Fotografie, Galerie U in Baiersbronn, ab April 2015.
- Ausstellung „Kaffee – Menschen – Kunst“ über das Kaffeeland Guatemala im Neuen Rathaus Altensteig, Juli – September 2016.
- Ausstellung „ Naturreine Interpretationen“ in Berlin Sommer 2017 zur IGA 2017
- Ausstellung „Olifant“ im Rathaus Freudenstadt Sommer/Herbst 2017
- Ausstellung WÄLDER im Haus des Waldes in Stuttgart
- Ausstellung Menschen in Burundi in Berlin 2018-12-13

**Lorem Ipsum**

Buch „WÄLDER in Baden Württemberg“ zusammen mit Forst BW 2017
Silberburg Verlag, Tübingen ISBN 978-3-8425-2038-7
```

**Comment by sylvainjule** [comment]
Are you using the latest version of the field?
This should have fixed it a few days ago: https://github.com/sylvainjule/kirby-markdown-field/commit/514f88ffc0d3f116cf1cfe2a930f4aa5477a6039

I haven't the issue anymore, no problem with your text.

**Comment by medienbaecker** [comment]
Yes, I'm using the latest version. Just downloaded it again and reproduced it with the text from above.

I guess we need to find the differences between our setups/installations. Are you on a Mac? I can test it on a Windows PC.

**Comment by sylvainjule** [comment]
Hmm. I'm also on a Mac (10.13.6), running a PHP 7.1.0 server with Mamp Pro, and having it successfully display on Chrome / FF / Safari, with the latest version on the field and latest RC.

One last thing to make sure the latest field is correctly running, has your `index.js` been rebuilt after updating the plugin? Have you or could you delete the `media/plugins/.index.js` file to force Kirby to rebuild it?

**Comment by medienbaecker** [comment]
I'm on 10.14.2, but I don't think that makes a huge difference.

I have cleaned up the media folder, downloaded the RC2 plainkit again, installed the markdown field again. Still the same. Here's a zip of my installation: http://backofen.link/plainkit.zip

Just to make sure we're doing the same thing to reproduce it:
1. Open the page with the markdown field
2. Paste the text from above
3. Text is invisible

It gets loaded correctly when viewing the page with the saved content.

**Comment by sylvainjule** [comment]
Thanks for your help reproducing this Thomas!

Should be fixed with : https://github.com/sylvainjule/kirby-markdown-field/commit/e68c5235fcbdfe1e1f52b49baf019342fc601e79
