### ISSUE TITLE
Toggle formatting

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#23]
Triggering a format action on an already formatted text should toggle the formatting.

![bold2](https://user-images.githubusercontent.com/7975568/50479725-3ea38300-09d8-11e9-9bba-94482eaacb97.gif)

**Comment by sylvainjule** [comment]
Yep, I agree.
First step was mimicking the textarea behaviour, I'll get on this next.

Clicking on an inline dropdown item should also place the # in front of the whole line, not the current caret position. 

Should toggle:
- Bold
- Italic
- Headlines
- Blockquotes
- Ul (from list item to paragraph)
- Ol (from list item to paragraph)

We could also have an active state for buttons whose styles are applied to the current selection / caret position.

**Comment by fabianmichael** [comment]
@sylvainjule Some of these features are in the VIsualMarkdown plugin for Kirby 2, we can probably re-use most of that code.

**Comment by sylvainjule** [comment]
Oh nice, I'll look into it.

**Comment by sylvainjule** [comment]
As a reminder,

**Buttons with specific actions, keep them as they are:**

- Horizontal rule
- Email
- File
- Image
- Link
- Pagelink

**Toggle character before the entire (/each) line:**

- [ ] Blockquote
- [ ] Headlines
- [ ] Ol
- [ ] Ul

**Toggle wrap:**

- [ ] Bold
- [ ] Italic
- [ ] Strikethrough
- [ ] Code

**Comment by sylvainjule** [comment]
Got started on an active state detection for buttons: https://github.com/sylvainjule/kirby-markdown-field/commit/6d365b233938cbf67eac76ce2d5886d948b672a9

![screen recording 2018-12-28 at 12 38 pm](https://user-images.githubusercontent.com/14079751/50514366-01092d80-0a9e-11e9-8973-3130fa69445b.gif)

I've had a look at the visual markdown field, the headline behavior is exactly what we need!

Formating isn't toggling there though, we'll still need to come up with our own implementation.

**Comment by sylvainjule** [comment]
Please give this branch a shot and let me know any issue: https://github.com/sylvainjule/kirby-markdown-field/pull/31

**Comment by medienbaecker** [comment]
Should the text selection persist after toggling the formatting? Not sure how useful that is apart from making gifs toggling it on and off, though. What do you think?

SimpleMDE:

![simplemde](https://user-images.githubusercontent.com/7975568/50535938-5f421900-0b4f-11e9-9b63-655dc61d9d11.gif)

Markdown:

![markdown](https://user-images.githubusercontent.com/7975568/50535995-15a5fe00-0b50-11e9-9824-058b403b4c4e.gif)

**Comment by sylvainjule** [comment]
I went for this behavior because I figured the reason you'd select the text in the first place was to apply the style, so there not much point keeping the selection afterwards. I've always been a bit bothered by selection persistence in these cases.

**Comment by medienbaecker** [comment]
Totally agree. Good old Microsoft Word keeps the selection afterwards. But I guess the times you accidentally apply the wrong formatting or want to "double format" are pretty rare.

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/pull/31
