### ISSUE TITLE
Toolbar loses its stickiness in Safari

### ISSUE THREAD

**Issue by paulrobertlloyd** [sylvainjule/kirby-markdown-field#32]
When a blueprint has `type: textarea`, the toolbar’s stickiness behaves correctly (i.e. it remains stuck to the top of the viewport when text area has focus and as you scroll up and down). Yet upon setting `type: markdown`, this behaviour is broken, with the toolbar remaining fixed in position as you scroll. This is only the case in Safari†, in other browsers (Firefox and Chrome) everything works as expected.

† Safari Technology Preview Release 72 (Safari 12.1, WebKit 14607.1.17.1) and Safari 12.0.2

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/c94339d1c1751864d0d170203ba5e294d554ed77 ✅
