### ISSUE TITLE
[CSS] Some font-sizing / styling questions

### ISSUE THREAD

**Issue by sylvainjule** [sylvainjule/kirby-markdown-field#34]
**1. Decrease monospace font-size?**

Shouldn't we decrease a little the monospace font-size (`font-size: $font-size-small`), so that it keeps the vertical rythm of the textarea field? It currently feels a bit big.
With the change:

<img width="1260" alt="capture d ecran 2018-12-30 a 17 30 18" src="https://user-images.githubusercontent.com/14079751/50557522-59327080-0ce6-11e9-91c7-ebd13cd1e52b.png">
<img width="1252" alt="capture d ecran 2018-12-30 a 17 31 23" src="https://user-images.githubusercontent.com/14079751/50557523-59327080-0ce6-11e9-9463-c95ac071461a.png">

**2. Sans-serif headlines**

Currently, h6 ends up being 14px while a regular paragraph is 16px.
Shouldn't we adjust those proportions so that h6 = paragraph?

**3. Font-styling options**

Should we give devs the possibility to disable the scaling of headings when displaying sans-serif?

Options could become:

```yaml
font:
  family: sans-serif
  scaling: false
```

**Comment by medienbaecker** [comment]
+1 for adjusting the font size.

Would `scaling: true` then also enable heading scaling for the monospace variant? While not literally "mono space" then, I think kinda miss the different sized headings in the default field.

**Comment by sylvainjule** [comment]
I guess it could be available for both, with default for sans-serif being `true` and default for monospace being `false`?

**Comment by medienbaecker** [comment]
Regarding the header proportions:

Personally I rarely (never) use all 6 headers, but h6 being smaller than a paragraph is still bad. In my opinion h5 and h6 could both be paragraph size.

**Comment by fabianmichael** [comment]
I noticed that headline font sizes for h5 and h6 where a bit goofy when I wrote the styles, but did not spend too much attention to this, as I barely use them at att. If this can be improved, I’m quite happy with it. Just did not want to make the H1 and H2 too large, but IMHO visual hierarchy between the different headers is not a important in the frontend, as we got the Markdown indicators for the headline levels to make them distinguishable from each other as support, while other tricks like e.g. color, underline, capitalization etc. are not available.

@sylvainjule I’m okay with making the monospace a little smaller, but everything below 15px brings me close to the edge of my comfort-zone. Other software like iA Writer also tends to rather large font sizes and I am quite happy with that (although I got good vision). For my current personal project, I am creating all texts directly in the panel (already using our Markdown field) and it just feels right, having it at 16px with a line-height of 28px, which gives it a bit more room to breathe. Is it really that important, that the vertical rhythm stays the same between monospace and sans-serif? IMHO, this would only look a bit odd once you got 2 columns side-by-side with them having different types of textareas.

@medienbaecker @sylvainjule I’m not really a big fan of the idea, but requirements and personal preferences are different. So I am not against this. :-)

**Comment by sylvainjule** [comment]
I have fixed the h6 font-size: https://github.com/sylvainjule/kirby-markdown-field/commit/8f851fe36f12f3b073a1301108926c65bd842a05

Also, I have tried to come up with some compromise regarding the font size and scaling options (https://github.com/sylvainjule/kirby-markdown-field/commit/b4424b2553761d85fab914176e231c116eaf297f).
The font options will now return an object:

```yaml
buttons:
  family: monospace
  scaling: false
  size: regular
```

Scaling will be `false` by default for monospace, and `true` for sans-serif, if the `scaling` option isn't explicitely set. 
`regular` and `small` sizes will allow to switch between 16px (default) and 14px. It can be set as a global option as any other props we've added, so decreasing the font-size will 

@fabianmichael I get your point, but I think it differs quite a lot depending on use cases. My issue with the 16px monospace isn't much about the misalignment with the textarea field, but the fact that with a way taller baseline + much wider words, even a short text can end up taking a lot of space in the panel if the field isn't full-width. So, whether the field is used to comfortably edit a long article, or if you have it 5x on a page to set 5-10 lines text blocks each time, requirements may differ.

I think the above options makes it flexible enough. Please reopen if it doesn't.
