### ISSUE TITLE
Long HTML tags explode writing area width

### ISSUE THREAD

**Issue by jschopplich** [sylvainjule/kirby-markdown-field#41]
I am using the `pages` preset with the bigger one (⅔ ratio) using a `type: markdown` field. No custom plugin configuration. I guess there's nothing else to say. 🙂 

![grafik](https://user-images.githubusercontent.com/27850750/50599477-86317f80-0eae-11e9-9e5a-14aa56c5d46c.png)

**Comment by sylvainjule** [comment]
Oh boy.

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/48e22e3345e32fda80d5829a7e92332c891347fe
