### ISSUE TITLE
Initial numbering of numbered lists

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#42]
I noticed that new lines in numbered lists now automatically increment the number.
That may not be required in terms of functionality, but it's definitely nice to have.

When formatting lines of text to a numbered list, it doesn't do the same, though:

![numlist](https://user-images.githubusercontent.com/7975568/50612551-9c553500-0eda-11e9-8375-605f2ed0bd2f.gif)

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/88c55aa5879622a09dad45a4cce860b65c1a04db ✅
