### ISSUE TITLE
Registration of custom buttons

### ISSUE THREAD

**Issue by sylvainjule** [sylvainjule/kirby-markdown-field#43]
It would be great to be able to easily add custom buttons. The current issue is the order in which components are loaded. 

Currently, each button (eg. `bold`) will look for a corresponding `k-mardown-button-bold` component, which contains a bunch of things:

- Its template (which only the headlines button overrides)
- Some data:

```javascript
data() {
  return {
    label: 'My label', // Shown on hover
    icon: 'my-icon', // Displayed in the toolbar
    type: 'my-button-type', // Used to identify whether the current selection is within the associated token type
    shortcut: 'Cmd-B', // Shortcut that should trigger the action (optional)
  }
}
```

- An `action` method, triggered on click or shortcut:

```javascript
methods: {
  action() {
    alert('It works!')
  }
}
```

All buttons extend a base button ([button.vue](https://github.com/sylvainjule/kirby-markdown-field/blob/master/src/components/toolbar/buttons/button.vue)).

So, in theory, one could create custom buttons by registering a component in another plugin, with as little config as:

```javascript
panel.plugin('my/methods', {
  components: {
    'k-markdown-button-test': {
      extends: 'k-markdown-button',
      data: function() {
        return {
          label: 'My label',
          icon: 'my-icon',
        }
      },
      methods: {
        action() {
          alert('It works!')
        }
      }
    },
  },
});
```

And then in a blueprint:

```yaml
mymarkdownfield:
  type: markdown
  buttons:
    - test
```

The issue is: how could we set it up so that `k-markdown-button` is available to extend by the time `k-markdown-button-test` tries to?

**Comment by sylvainjule** [comment]
I guess one issue is that the panel is storing available components before the registration begins (https://github.com/k-next/kirby/blob/33f2108d9016c5ed1aad0cc942e37c2f09dd62c9/panel/src/config/plugins.js#L7-L9), and then checks the required `extends` component name against this cached array (https://github.com/k-next/kirby/blob/33f2108d9016c5ed1aad0cc942e37c2f09dd62c9/panel/src/config/plugins.js#L21), so even if the main button was added to `Vue.options.components` before the custom button tries to access it, Kirby won’t find it on the fly. 🤔

**Comment by medienbaecker** [comment]
Is this still on hold? I guess "plugins for plugins" is something that should be possible — not only for the markdown field.

**Comment by flokuek** [comment]
I think this would be very handy to include a custom kirby tag via a custom button :)

**Comment by sylvainjule** [comment]
Definitely agree, but to do this properly we have to wait for https://github.com/getkirby/ideas/issues/23

**Comment by Foddy** [comment]
Is this possible now? I would also love to create some custom buttons 👍 !

**Comment by janstieler** [comment]
Hi,
on Kirby 3.3.0 hooks for plugins are deployed.
https://github.com/getkirby/kirby/pull/2014/files
https://getkirby.com/docs/reference/plugins/extensions/hooks

Have someone a cookbook for using this for own buttons?

Cheers

**Comment by sylvainjule** [comment]
This is now possible (thanks to @bastianallgeier, I borrowed the registration logic from the Editor).

Documented [here](https://github.com/sylvainjule/kirby-markdown-field/tree/master/custom-buttons).
