### ISSUE TITLE
Kirby translations return nothing with activated plugin

### ISSUE THREAD

**Issue by jschopplich** [sylvainjule/kirby-markdown-field#44]
Using:
- Kirby 3.0 RC3
- this plugin in latest version
- no other plugins

In a setup using two languages (`de` & `en`) the `t()` helper returns nothing at all across different pages.

For example use the following language file with `t('t.test')`:

```php
<?php

return [
  'code' => 'de',
  'default' => true,
  'direction' => 'ltr',
  'locale' => 'de_DE.utf8',
  'name' => 'Deutsch',
  'url' => '/',

  'translations' => [
    't.test' => '&larr; Hi',
  ]
];
```

**Comment by sylvainjule** [comment]
Are you sure it's due to the plugin? 
cf. https://github.com/k-next/kirby/issues/1307

**Comment by jschopplich** [comment]
I see. Seems to be a core issue. Narrowed it down to your plugin because without it everything worked as expected. How misleading.
