### ISSUE TITLE
Kirby revert/undo button not working

### ISSUE THREAD

**Issue by littlemermaidfromthesea** [sylvainjule/kirby-markdown-field#47]
Could it be that the revert/undo button isn't working properly? 
RC3, Safari, Firefox

**Comment by sylvainjule** [comment]
Some additional details might be useful: what do you mean by not working? Nothing happens ? Reverts to the wrong content? I don't seem to have issues with revert on FF or Safari, could you guide me through some exact steps causing issues for you?

**Comment by littlemermaidfromthesea** [comment]
Hey! Yeah like you said, the field is not reverting any changes, nothing happens. The content just stays the same as after editing. I only tested the link and bold button though.

Today I ran into another issue in Safari only: if the textarea is bigger than the window, after scrolling and then clicking on a button in the toolbar, the toolbar loses focus and its sticky position. According to the helpdesk slack, this is a Kirby issue not a plugin issue.

**Comment by sylvainjule** [comment]
I am also testing it in a multilanguage installation though, and don't have the revert issue. Any other plugin installed? Any error thrown in the console?

I have identified the second safari issue and am pushing a fix, thanks for the heads up!

**Comment by littlemermaidfromthesea** [comment]
No, this is the only plugin I installed. It works as intended if it's a regular textarea field.

**Comment by sylvainjule** [comment]
Could you zip me your install? Removing the sensitive parts.

**Comment by sylvainjule** [comment]
Ok, could reproduce it when there is 2+ field on the page. Will look into it.

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/cbe34ee51e340ead470652c871c485e41b2a0171
