### ISSUE TITLE
A lot of console range errors in Safari after RC4 Update if using the link button.

### ISSUE THREAD

**Issue by littlemermaidfromthesea** [sylvainjule/kirby-markdown-field#48]
Hey! Sorry to be a pooface.
I just ran into the following errors (see screenshots). They only occur if I use the link-button and a modal window opens. Not with bold for instance.

<img width="993" alt="bildschirmfoto 2019-01-08 um 19 56 05" src="https://user-images.githubusercontent.com/42815796/50852412-be89ff80-137f-11e9-8a4e-2c0ed173b007.png">
<img width="991" alt="bildschirmfoto 2019-01-08 um 19 56 13" src="https://user-images.githubusercontent.com/42815796/50852414-bf229600-137f-11e9-9f4a-00f85b34b9d3.png">

**Comment by sylvainjule** [comment]
I could really use you current installation to try and debug this too, because I can't reproduce either.

**Comment by littlemermaidfromthesea** [comment]
Hm, how do I do that? Do I just upload the whole directory somewhere?

**Comment by littlemermaidfromthesea** [comment]
Ah, it happens if there's more than one markdown field on the page.

**Comment by littlemermaidfromthesea** [comment]
Cool, thx.

**Comment by sylvainjule** [comment]
https://github.com/sylvainjule/kirby-markdown-field/commit/c68faef8cf8807de0988dbffa4b6c14271a6d809
