### ISSUE TITLE
[Feature Request] 'Query' Option for Images

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-markdown-field#54]
The `query` option that we have for pagelink could also be useful for the image picker. Here is the use-case: I am building a one-pager, where each of the page's sections is a child page. Each one of these child pages will use the markdown field, and all of them will need to embed images into the field. 

However, as they are all really part of the _same parent page_, rather than having to add a Files Section on each child page, allowing the user to upload images into each individual child page, I'd rather just add a single Files Section in the _parent_ page. Ideally, the user would be able to then pick the images **from the parent page** - not from the current one.

This would be important also in avoiding multiple uploads of the same image, that are being used in different sections of the same page.

That is, of course, just one use-case, and I'm sure there will be others.

**Comment by sylvainjule** [comment]
Added, https://github.com/sylvainjule/kirby-markdown-field/commit/dc957ad028ccb8bdd080a4795265bc29a78bef71.
Please give it a shot and let me know it it works for you. :)
