### ISSUE TITLE
Kirbytags highlight problem if parenthesis

### ISSUE THREAD

**Issue by SamuelRiversMoore** [sylvainjule/kirby-markdown-field#60]
Hi, there is a problem with the highlights of kirbytags when there is some parenthesis inside it...

Screenshot :
![capture d ecran du 2019-01-28 10-52-18](https://user-images.githubusercontent.com/2640748/51828027-f636f800-22ea-11e9-8e24-19761a8735df.png)

**Comment by medienbaecker** [comment]
Isn't that problematic anyway? I remember seeing lots of Forum posts about it over the years. Not sure if Kirby 3 changed this, but I think you'd need to escape them anyway: https://forum.getkirby.com/t/escape-kirbytag-parenthesis/8300

**Comment by SamuelRiversMoore** [comment]
Hm. Ok so obviously it's more a general kirbytext parsing problem... Sorry for the issue. 
Of course it's not that problematic but the fact the rendering seems buggy isn't very engaging, especially for those who are willing to use of the kirbytext field with custom kirbytags...

**Comment by SamuelRiversMoore** [comment]
> That's better than showing a "correct" highlighting and then butchering it in the output in my opinion.

Indeed!

**Comment by sylvainjule** [comment]
I agree that although not visually satisfying, mimicking the output is the most helpful here. 🤔 

Thus I'm closing this issue, please feel free to open a new ticket as soon as kirbytag's parsing changes / the idea above gets implemented, if we miss it.
