### ISSUE TITLE
 Browser jumps to top if no file is selectet

### ISSUE THREAD

**Issue by thomasfahrland** [sylvainjule/kirby-markdown-field#61]
If a page contains no files and I click on the file or picture button in the editor, the browser jumps up.
![bug](https://user-images.githubusercontent.com/24317084/52040709-959cfa80-2538-11e9-84f6-1536686e08dd.gif)

kirby-markdown-field: latest (1c61f8f ) and also older version
Kirby: 3.0.0
Mac OSX, Google Chrome latest (70.x)

**Comment by sylvainjule** [comment]
Hmm, just had a look and I'm not sure if I can fix this.

When this happens, Kirby catches the invalid : empty query and opens an error dialog that doesn't seem to emit a unique global event, so the field cannot catch it to bring the focus back. 🤔
