### ISSUE TITLE
Background is splitted by returns in code blocks

### ISSUE THREAD

**Issue by LeBenLeBen** [sylvainjule/kirby-markdown-field#62]
It would be awesome if the background could cover the entire block.

![capture d ecran 2019-02-03 a 11 34 58](https://user-images.githubusercontent.com/793344/52175695-f2521c80-27a7-11e9-82ac-d079b24dd929.png)

**Comment by fabianmichael** [comment]
Okay, I thought I already fixed that (just tried myself and yeah … it’s still broken), but will have another look at the issue.

**Comment by fabianmichael** [comment]
@LeBenLeBen I changed a few settings in the highlighter and committed them to a branch (see above). Please test, if it fixes your problem without causing any others. If so, I’ll merge into master.

**Comment by LeBenLeBen** [comment]
@fabianmichael Thanks, I'll give it a try asap and come back to you.

**Comment by LeBenLeBen** [comment]
@fabianmichael I've checked out your branch and the problem seems to be still occurring.

I've installed with:
```json
"k-community/markdown-field": "dev-feature/62-codeblocks-background as 1.0-dev",
```

The file you changed seems to be updated in the source. I've force refreshed the dashboard to be sure  but no chance.
