### ISSUE TITLE
Pagelink does not return correct url for multilanguage site

### ISSUE THREAD

**Issue by SebastianEberlein** [sylvainjule/kirby-markdown-field#64]
In a Kirby site with multiple languages, the Pagelink does not return the translated url.

**Kirby starterkit example:**

About page url in English: `en/about`
About page url in German: `de/ueber-uns`

When I change the language to German and use the page link to select the about page, the kirbytag that is created looks like this: `(link: about text: Link to About)`. 

But should be `(link: de/ueber-uns text: Link to About)`.

**Comment by sylvainjule** [comment]
It actually seems to be the correct behavior, the page dialog doesn't return any other uri, even when used separately the pages field stores the default language uri in the content file. The correct url is then retrieved with the `toPage` method.

The `link` tag accepts a[lang parameter](https://github.com/getkirby/kirby/blob/d62cc7536a709f8346eb2b1a066db835e0372128/config/tags.php#L147-L149) though, to retrieve the correct url when formatted. This is what I've added in https://github.com/sylvainjule/kirby-markdown-field/commit/e66b779492a5d7aa54271c723ffd45c7c8d8ca05, whenever you're adding a link in a non-default language, the lang parameter will be automatically filled.
