### ISSUE TITLE
Add option to disable tabs

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#66]
While using the markdown field as a replacement for the textarea field I realized I could no longer tab between fields. That's especially noticeable inside structure fields.

**Comment by fabianmichael** [comment]
I think, we already got enough options for now and using the tab key inside a web form is rather unexpected behavior as long as you’re not in a code editor. I disabled the tab key for all instances of the editor.

**Comment by medienbaecker** [comment]
While pressing tab works now, pressing shift + tab to go back one field does not.

**Comment by medienbaecker** [comment]
@fabianmichael Can you please reopen this issue?
