### ISSUE TITLE
Multiple modals and page timeout when using multiple fields within builder plugin

### ISSUE THREAD

**Issue by jakobploens** [sylvainjule/kirby-markdown-field#69]
Seems related to #48, but in every browser. The same error message is logged to console (at least in Safari), but the issue is also visible in Chrome and Firefox. When having two or more markdown fields within a page using the builder plugin (one module multiple times), clicking one of the buttons wich trigger a modal (link, email) opens up two (or more) modals and the site freezes.

**Comment by sylvainjule** [comment]
Does the latest release fix the issue?

**Comment by sylvainjule** [comment]
Just tested it with the builder and 3.0.3, it seems fixed on my end. Feel free to reopen if not.
