### ISSUE TITLE
Pagelink does not return correct model url

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#72]
When overwriting the `->url()` function in a page model like this:

```
class SectionPage extends Page {
	public function url($options = null): string {
		return $this->parents()->first()->url() . '#' . $this->slug();
	}
}
```

…the pagelink button still inserts a regular url into the `(link:` kirbytag.

**Comment by sylvainjule** [comment]
Does the pages field save the correct url for the same page?

**Comment by medienbaecker** [comment]
Nope! So I guess this is more a core issue?

**Comment by sylvainjule** [comment]
The dialog actually uses the `id` of the page, never its url, can you try overwriting that?

**Comment by medienbaecker** [comment]
Overwriting the `->id()` function surprisingly works, too:

```php
public function id(): string {
        return $this->parents()->first()->uid() . '#' . $this->slug();
}
```
But this also changes the links to that page in the panel, making it unusable/inaccessible.

I don't think this is something you can fix in the markdown field, though. Sorry for the misunderstanding and thanks for your time, Sylvain!
