### ISSUE TITLE
Field not initiated in collapsed builder field

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-markdown-field#77]
This happens when using the markdown field in a [builder field](https://github.com/TimOetting/kirby-builder) and you're loading a page with collapsed fieldsets:

![builder-markdown](https://user-images.githubusercontent.com/7975568/60579456-6c9cc200-9d83-11e9-8dcf-3302f757ac95.gif)

To me it looks like the field "forgets" to initiate at the un-collapse event.

**Comment by falkmueller** [comment]
Hi,

here my solution:

Subscribe a event to refresh the editor:
**site/plugins/kirby-markdown-field/src/components/input/MarkdownInput.vue Line 102**
```
  mounted() {
...
    window.addEventListener('kirby-bulder.expandBLock', () => {
            this.$nextTick(() => this.editor.refresh())
    });
}
```

Fire a event by open a tab in the kirby-builder:
**site/plugins/kirby-builder/src/components/BuilderBlock.vue Line 278**

```  
toggleExpand(expanded) {
...
      if(this.expanded){
        window.dispatchEvent(new Event('kirby-bulder.expandBLock'));
      }
}
```

**Comment by sylvainjule** [comment]
@medienbaecker is it still happening for you with Kirby 3.2.5+, the latest builder and the latest markdown field?

Seems fixed on my end.

**Comment by medienbaecker** [comment]
@sylvainjule I just reproduced it in Kirby 3.3.0-rc.3 with the latest builder and markdown field:

![builder-markdown](https://user-images.githubusercontent.com/7975568/68104521-af120f00-fedb-11e9-86a0-086512cf6fea.gif)

It only works (or doesn't) when you load a page with already collapsed builder blocks.
