### ISSUE TITLE
Smart Quotes

### ISSUE THREAD

**Issue by luxuryluke** [sylvainjule/kirby-markdown-field#80]
Is there any way for smart quotes to be inserted while typing in a markdown textarea outside of a code block?
A customer is particularly sensitive about smart quotes.

**Comment by fabianmichael** [comment]
Nope, but Kirby has a built-in Smartypants parser and field method. You can add smart quotes by calling the `$field->smartypants()` method in your templates.

See https://getkirby.com/docs/reference/templates/field-methods/smartypants

**Comment by luxuryluke** [comment]
Oof, I feel like a dolt, now. Cheers!
