### ISSUE TITLE
Linking to other pages failing on Kirby 3.3

### ISSUE THREAD

**Issue by luxuryluke** [sylvainjule/kirby-markdown-field#85]
I updated to Kirby 3.3 today and tried out the Editor, which went mostly brilliantly.
I think having this plugin installed next to the Editor plugin may not work well side by side, or my code is malformed. So I've uninstalled the Editor for now. I prefer the power that's available in this plugin for now.

Either way, your hybrid textarea plugin works wonderful, and I've been using it all turned on, preview, etc.

The 'link to page on site' button didn't work though. It returned this:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/57873/68260314-89772980-fff1-11e9-9b51-04792f41d99d.png">

I've restarted Safari on Desktop 13.0.3 (which fixed a few things in the new Kirby update, it may have been cache, etc.) but the problem still exists. 

Hopefully you're able to track down why this is working without too much trouble.

Linking to other pages is powerful. Thanks for such a wonderful tool.

**Comment by luxuryluke** [comment]
It looks like you've updated some things in the last five days and I haven't updated your plugin for weeks. I'll give a fresh install a shot.

**Comment by medienbaecker** [comment]
I experience a similar error on Kirby 3.3 using the latest version of this field:

![image](https://user-images.githubusercontent.com/7975568/68297147-7c604600-0096-11ea-9958-880aa5d77611.png)

Latest Chrome, empty media folder, only on clicking the page link button.

**Comment by Werbschaft** [comment]
Same for me ...
