### ISSUE TITLE
Image-Button: Search field returns error

### ISSUE THREAD

**Issue by CrisGraphics** [sylvainjule/kirby-markdown-field#87]
When trying to insert an image, the search field of the modal returns the following error: `No route found for path: "null" and request method: "GET"`

Chrome 77
Kirby v3.3.1

Edit: I don't know, if I should open a another issue for that, but the same error occurs with the File-Button

**Comment by CrisGraphics** [comment]
I don't know, if I should open a another issue for that, but the same error occurs with the File-Button

**Comment by janherman** [comment]
Maybe it is somehow connected to [this](https://github.com/getkirby/kirby/issues/2388#issue-548420306)? It could be a problem of Kirby itself.

**Comment by oneismore** [comment]
I tested on a freshly downloaded 3.3.2 and got the same error. Also the search does not work with the normal textarea in this version of Kirby (nothing happens). I replaced Kirby with 3.3.3rc1 (with the fix from https://github.com/getkirby/kirby/issues/2388) and the search for the textarea now works again. But alas the markdown field still shows the same error.
