### ISSUE TITLE
Input text gets rendered italic after using target: _blank option

### ISSUE THREAD

**Issue by trych** [sylvainjule/kirby-markdown-field#89]
![20200210-152143_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/74157809-3678c800-4c19-11ea-8ed9-bc7ff796e682.png)

See screenshot. The underscore seems to be interpreted as a Markdown statement and renders the following input text italic. In the regular kirbytext input field this is escaped somehow and does not happen.

**Comment by medienbaecker** [comment]
Duplicate of https://github.com/sylvainjule/kirby-markdown-field/issues/65

**Comment by trych** [comment]
Oh, sorry, didn't see that. More users are having this problem as well, see [this post](https://forum.getkirby.com/t/markdown-field-plugin-target-blank-in-a-link-makes-following-text-italic/17202) in the Kirby forums.

Will close this.
