### ISSUE TITLE
Error Page on Installation

### ISSUE THREAD

**Issue by unrulybeep** [sylvainjule/kirby-markdown-field#90]
Greetings all,

I am starting my journal with Kirby, and your plugin is the first I have tried. I followed the instructions, as in I download and copied contents to /site/plugins/markdown-field, and replaced textarea with
```
     editor:
          label: My markdown editor
          type: markdown
```
in my blueprints. However, when I attempt to create pages which have the markdown type I receive the following error: The markdown field is missing. Please add it to your installed fields or remove it from your blueprint

Could you please advise me? Thank you.

**Comment by oneismore** [comment]
If you rename the folder from ```/site/plugins/markdown-field``` to ```/site/plugins/kirby-markdown-field``` it should work ;)

**Comment by sylvainjule** [comment]
Apologies for the delay. 

Actually, the field should be loaded no matter the name you give to the plugin.

Do you still have the issue? What's the Kirby version?

**Comment by sylvainjule** [comment]
Closing this issue, don't hesitate to reopen if needed.
