### ISSUE TITLE
Is there a way to control the output?

### ISSUE THREAD

**Issue by thomasverleye** [sylvainjule/kirby-markdown-field#92]
Hi,

Love this plugin!
Is there a way to render a h1 as a h2?

Been searching the web for a sort of filter on the kirbytext but couldn't seem to find anything.

Cheers!

Thomas

**Comment by medienbaecker** [comment]
There's a great plugin for things like that:
https://github.com/hananils/kirby-tree-methods#adjusting-headline-hierarchy
