### ISSUE TITLE
How to set the headlinebuttons in a global config?

### ISSUE THREAD

**Issue by janstieler** [sylvainjule/kirby-markdown-field#99]
Hi,
how can I reduce the headline buttons in the global configuration?
In your readme is only a instruction for all headline buttons. I don't need a H1-button.

Cheers

**Comment by matthacksteiner** [comment]
Any news on this? Would love to have this option...

**Comment by cadars** [comment]
This works, except the headlines button is now last?
```
 'community.markdown-field.buttons' => [
    'headlines' => ['h2', 'h3', 'h4'], 'bold', 'italic', 'divider', 'ul', 'ol', 'footnote', 'code', 'divider', 'link', 'email'
 ], 
```
![image](https://user-images.githubusercontent.com/467112/99057638-62581e00-259c-11eb-9134-4e613b93460d.png)

**Comment by sylvainjule** [comment]
You can set it like this:

```php
'community.markdown-field' => [
    'buttons' => [['h2', 'h3', 'h4'], 'bold', 'italic', '...'],
]
```

**Comment by janstieler** [comment]
Does this work further?
with:
```yml
    'community.markdown-field' => [
        'buttons' => [['h2', 'h3', 'h4', 'h5', 'h6'], 'bold', 'italic', 'strikethrough', 'code', 'ul', 'ol', 'link', 'blockquote', 'hr', 'strikethrough', 'highlight', 'pagelink', 'file', 'footnote', 'invisibles', 'divider'],
    ],
    ```
    I get only the standard buttons displayed and not all.

**Comment by janstieler** [comment]
> Does this work further? with:
> 
>     'community.markdown-field' => [
>         'buttons' => [['h2', 'h3', 'h4', 'h5', 'h6'], 'bold', 'italic', 'strikethrough', 'code', 'ul', 'ol', 'link', 'blockquote', 'hr', 'strikethrough', 'highlight', 'pagelink', 'file', 'footnote', 'invisibles', 'divider'],
>     ],
> I get only the standard buttons displayed and not all.

Any new information about? I run again in this problem on a actual project.

**Comment by fabianmichael** [comment]
@janstieler Sorry for the silence … in version 2, global buttons configs habe been removed. I recommend to use re-usable field blueprints insteas.

**Comment by janstieler** [comment]
Thanks @fabianmichael to clarify how it works now.
